apiVersion: v1
kind: Service
metadata:
  name: great-expectations
  namespace: datalyptica-management
  labels:
    app: great-expectations
    layer: analytics
spec:
  type: ClusterIP
  selector:
    app: great-expectations
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
