apiVersion: v1
kind: Service
metadata:
  name: loki-read-headless
  namespace: datalyptica-management
  labels:
    app: loki
    component: read
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: loki
    component: read
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loki-read
  namespace: datalyptica-management
  labels:
    app: loki
    component: read
spec:
  type: ClusterIP
  selector:
    app: loki
    component: read
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loki-write-headless
  namespace: datalyptica-management
  labels:
    app: loki
    component: write
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: loki
    component: write
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loki-write
  namespace: datalyptica-management
  labels:
    app: loki
    component: write
spec:
  type: ClusterIP
  selector:
    app: loki
    component: write
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loki-backend-headless
  namespace: datalyptica-management
  labels:
    app: loki
    component: backend
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: loki
    component: backend
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loki-backend
  namespace: datalyptica-management
  labels:
    app: loki
    component: backend
spec:
  type: ClusterIP
  selector:
    app: loki
    component: backend
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
