apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datalyptica-storage

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - pdb.yaml

commonLabels:
  platform: datalyptica
  tier: storage
  component: postgresql
  cluster-name: postgresql-ha
