apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datalyptica-management

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - configmap.yaml
  - daemonset.yaml
  - service.yaml

commonLabels:
  app: alloy
  component: logging
  managed-by: kustomize
