apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: datalyptica-management
  labels:
    app: alloy
    component: logging
spec:
  clusterIP: None
  selector:
    app: alloy
  ports:
    - name: http
      port: 12345
      targetPort: http
      protocol: TCP
