---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datalyptica-management

resources:
  - prometheus grafana loki alertmanager alloy kafka-ui airflow jupyterhub mlflow superset great-expectations
