services:

  # Minio Service
  minio:
    image: ghcr.io/shugur-network/shudl/minio:latest
    container_name: ${COMPOSE_PROJECT_NAME}-minio
    environment:
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET_NAME}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=/data
      - MINIO_OPTS=--console-address :9001
      - MINIO_REGION=${MINIO_REGION}
    volumes:
      - minio_data:/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Postgresql Service
  postgresql:
    image: ghcr.io/shugur-network/shudl/postgresql:latest
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - PGDATA=/var/lib/postgresql/data/pgdata
      - SHUDL_DB=${SHUDL_DB}
      - SHUDL_USER=${SHUDL_USER}
      - SHUDL_PASSWORD=${SHUDL_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Nessie Service
  nessie:
    image: ghcr.io/shugur-network/shudl/nessie:latest
    container_name: ${COMPOSE_PROJECT_NAME}-nessie
    environment:
      - QUARKUS_HTTP_CORS_HEADERS=${NESSIE_CORS_HEADERS}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_INITIAL_SIZE=${NESSIE_DB_INITIAL_SIZE}
      - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
      - NESSIE_VERSION_STORE_TYPE=${NESSIE_VERSION_STORE_TYPE}
      - QUARKUS_DATASOURCE_POSTGRESQL_USERNAME=${POSTGRES_USER}
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - QUARKUS_HTTP_CORS_METHODS=${NESSIE_CORS_METHODS}
      - QUARKUS_HTTP_CORS_EXPOSED_HEADERS=${NESSIE_CORS_EXPOSED_HEADERS}
      - QUARKUS_HTTP_CORS_ACCESS_CONTROL_MAX_AGE=${NESSIE_CORS_MAX_AGE}
      - NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE=${NESSIE_DATASOURCE_NAME}
      - QUARKUS_DATASOURCE_POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_MIN_SIZE=${NESSIE_DB_MIN_SIZE}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - QUARKUS_HTTP_PORT=${NESSIE_PORT}
      - QUARKUS_HTTP_HOST=${NESSIE_HOST}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_URL=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_MAX_SIZE=${NESSIE_DB_MAX_SIZE}
      - QUARKUS_HTTP_CORS=${NESSIE_CORS_ENABLED}
      - QUARKUS_HTTP_CORS_ORIGINS=${NESSIE_CORS_ORIGINS}
    volumes:
      []
    networks:
      - ${NETWORK_NAME}
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19120/api/v1/info"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Trino Service
  trino:
    image: ghcr.io/shugur-network/shudl/trino:latest
    container_name: ${COMPOSE_PROJECT_NAME}-trino
    environment:
      - TRINO_DISCOVERY_URI=${TRINO_DISCOVERY_URI}
      - TRINO_QUERY_MAX_MEMORY=${TRINO_QUERY_MAX_MEMORY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - TRINO_COORDINATOR=${TRINO_COORDINATOR}
      - TRINO_NODE_SCHEDULER_INCLUDE_COORDINATOR=${TRINO_INCLUDE_COORDINATOR}
      - TRINO_HTTP_SERVER_PORT=${TRINO_PORT}
    volumes:
      []
    networks:
      - ${NETWORK_NAME}
    depends_on:
      minio:
        condition: service_healthy
      nessie:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Spark-master Service
  spark-master:
    image: ghcr.io/shugur-network/shudl/spark:latest
    container_name: ${COMPOSE_PROJECT_NAME}-spark-master
    environment:
      - SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY}
      - SPARK_ICEBERG_CATALOG_NAME=${SPARK_ICEBERG_CATALOG_NAME}
      - SPARK_ICEBERG_CATALOG_URI=${NESSIE_URI}
      - SPARK_ICEBERG_CATALOG_S3_PATH_STYLE_ACCESS=${S3_PATH_STYLE_ACCESS}
      - WAREHOUSE_LOCATION=${WAREHOUSE_LOCATION}
      - SPARK_SSL_ENABLED=false
      - SPARK_DRIVER_MAX_RESULT_SIZE=${SPARK_DRIVER_MAX_RESULT_SIZE}
      - SPARK_ICEBERG_CATALOG_TYPE=${SPARK_ICEBERG_CATALOG_TYPE}
      - SPARK_ICEBERG_CATALOG_IO_IMPL=${SPARK_ICEBERG_CATALOG_IO_IMPL}
      - SPARK_ICEBERG_CATALOG_S3_ENDPOINT=${S3_ENDPOINT}
      - SPARK_ICEBERG_CATALOG_S3_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - SPARK_ICEBERG_CATALOG_S3_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - SPARK_WEBUI_PORT=${SPARK_UI_PORT}
      - SPARK_RPC_AUTHENTICATION_ENABLED=false
      - SPARK_RPC_ENCRYPTION_ENABLED=false
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=false
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
      - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY}
      - SPARK_ICEBERG_CATALOG_WAREHOUSE=${WAREHOUSE_LOCATION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - SPARK_MODE=master
      - SPARK_EXECUTOR_CORES=${SPARK_EXECUTOR_CORES}
      - SPARK_EXECUTOR_INSTANCES=${SPARK_EXECUTOR_INSTANCES}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - NESSIE_URI=${NESSIE_URI}
    volumes:
      []
    networks:
      - ${NETWORK_NAME}
    depends_on:
      minio:
        condition: service_healthy
      nessie:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Spark-worker Service
  spark-worker:
    image: ghcr.io/shugur-network/shudl/spark:latest
    container_name: ${COMPOSE_PROJECT_NAME}-spark-worker
    environment:
      - SPARK_EXECUTOR_CORES=${SPARK_EXECUTOR_CORES}
      - SPARK_ICEBERG_CATALOG_TYPE=${SPARK_ICEBERG_CATALOG_TYPE}
      - SPARK_ICEBERG_CATALOG_WAREHOUSE=${WAREHOUSE_LOCATION}
      - SPARK_ICEBERG_CATALOG_IO_IMPL=${SPARK_ICEBERG_CATALOG_IO_IMPL}
      - SPARK_ICEBERG_CATALOG_S3_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - SPARK_ICEBERG_CATALOG_S3_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - SPARK_MODE=worker
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=false
      - SPARK_SSL_ENABLED=false
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
      - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY}
      - SPARK_ICEBERG_CATALOG_URI=${NESSIE_URI}
      - SPARK_ICEBERG_CATALOG_S3_PATH_STYLE_ACCESS=${S3_PATH_STYLE_ACCESS}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - SPARK_RPC_AUTHENTICATION_ENABLED=false
      - SPARK_ICEBERG_CATALOG_NAME=${SPARK_ICEBERG_CATALOG_NAME}
      - SPARK_ICEBERG_CATALOG_S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - SPARK_RPC_ENCRYPTION_ENABLED=false
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
    volumes:
      []
    networks:
      - ${NETWORK_NAME}
    depends_on:
      spark-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
  postgresql_data:
    driver: local

networks:
  shunetwork:
    name: ${NETWORK_NAME}
    driver: bridge
