services:

  # Minio Service
  minio:
    image: ghcr.io/shugur-network/shudl/minio:latest
    container_name: minio
    environment:
      - MINIO_REGION=${MINIO_REGION}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET_NAME}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=/data
      - MINIO_OPTS=--console-address :9001
    volumes:
      - minio_data:/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Nessie Service
  nessie:
    image: ghcr.io/shugur-network/shudl/nessie:latest
    container_name: nessie
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - QUARKUS_HTTP_PORT=${NESSIE_PORT}
      - QUARKUS_HTTP_CORS_HEADERS=${NESSIE_CORS_HEADERS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_INITIAL_SIZE=${NESSIE_DB_INITIAL_SIZE}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_MIN_SIZE=${NESSIE_DB_MIN_SIZE}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - QUARKUS_DATASOURCE_POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_MAX_SIZE=${NESSIE_DB_MAX_SIZE}
      - QUARKUS_HTTP_CORS=${NESSIE_CORS_ENABLED}
      - QUARKUS_HTTP_CORS_ORIGINS=${NESSIE_CORS_ORIGINS}
      - QUARKUS_HTTP_CORS_METHODS=${NESSIE_CORS_METHODS}
      - QUARKUS_HTTP_CORS_EXPOSED_HEADERS=${NESSIE_CORS_EXPOSED_HEADERS}
      - QUARKUS_HTTP_CORS_ACCESS_CONTROL_MAX_AGE=${NESSIE_CORS_MAX_AGE}
      - POSTGRES_DB=${POSTGRES_DB}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - QUARKUS_HTTP_HOST=${NESSIE_HOST}
      - NESSIE_VERSION_STORE_TYPE=${NESSIE_VERSION_STORE_TYPE}
      - NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE=${NESSIE_DATASOURCE_NAME}
      - QUARKUS_DATASOURCE_POSTGRESQL_USERNAME=${POSTGRES_USER}
      - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
    volumes:
      []
    networks:
      - ${NETWORK_NAME}
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19120/api/v1/info"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Postgresql Service
  postgresql:
    image: ghcr.io/shugur-network/shudl/postgresql:latest
    container_name: postgresql
    environment:
      - SHUDL_USER=${SHUDL_USER}
      - SHUDL_PASSWORD=${SHUDL_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - PGDATA=/var/lib/postgresql/data/pgdata
      - SHUDL_DB=${SHUDL_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

volumes:
  postgresql_data:
    driver: local
  minio_data:
    driver: local

networks:
  testnet:
    name: ${NETWORK_NAME}
    driver: bridge
