services:

  # Spark-master Service
  spark-master:
    image: ghcr.io/shugur-network/shudl/spark-master:latest
    container_name: ${COMPOSE_PROJECT_NAME}-spark-master
    environment:
      - SPARK_WEBUI_PORT=${SPARK_UI_PORT}
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - NESSIE_URI=${NESSIE_URI}
      - WAREHOUSE_LOCATION=${WAREHOUSE_LOCATION}
      - SPARK_MODE=master
    volumes:
      []
    networks:
      - ${NETWORK_NAME}
    depends_on:
      minio:
        condition: service_healthy
      nessie:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Spark-worker Service
  spark-worker:
    image: ghcr.io/shugur-network/shudl/spark-worker:latest
    container_name: ${COMPOSE_PROJECT_NAME}-spark-worker
    environment:
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
    volumes:
      []
    networks:
      - ${NETWORK_NAME}
    depends_on:
      spark-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Minio Service
  minio:
    image: ghcr.io/shugur-network/shudl/minio:latest
    container_name: ${COMPOSE_PROJECT_NAME}-minio
    environment:
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=/data
      - MINIO_OPTS=--console-address :9001
      - MINIO_REGION=${MINIO_REGION}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET_NAME}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    volumes:
      - minio_data:/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Postgresql Service
  postgresql:
    image: ghcr.io/shugur-network/shudl/postgresql:latest
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    environment:
      - SHUDL_USER=${SHUDL_USER}
      - SHUDL_PASSWORD=${SHUDL_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - PGDATA=/var/lib/postgresql/data/pgdata
      - SHUDL_DB=${SHUDL_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Nessie Service
  nessie:
    image: ghcr.io/shugur-network/shudl/nessie:latest
    container_name: ${COMPOSE_PROJECT_NAME}-nessie
    environment:
      - QUARKUS_DATASOURCE_USERNAME=${POSTGRES_USER}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - QUARKUS_HTTP_HOST=${NESSIE_HOST}
      - QUARKUS_DATASOURCE_POSTGRESQL_USERNAME=${POSTGRES_USER}
      - QUARKUS_DATASOURCE_POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - QUARKUS_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - QUARKUS_HTTP_PORT=${NESSIE_PORT}
      - NESSIE_VERSION_STORE_TYPE=${NESSIE_VERSION_STORE_TYPE}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_URL=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
    volumes:
      []
    networks:
      - ${NETWORK_NAME}
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19120/api/v2/config"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Trino Service
  trino:
    image: ghcr.io/shugur-network/shudl/trino:latest
    container_name: ${COMPOSE_PROJECT_NAME}-trino
    environment:
      - TRINO_DISCOVERY_URI=${TRINO_DISCOVERY_URI}
      - TRINO_QUERY_MAX_MEMORY=${TRINO_QUERY_MAX_MEMORY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - TRINO_COORDINATOR=${TRINO_COORDINATOR}
      - TRINO_NODE_SCHEDULER_INCLUDE_COORDINATOR=${TRINO_INCLUDE_COORDINATOR}
      - TRINO_HTTP_SERVER_PORT=${TRINO_PORT}
    volumes:
      []
    networks:
      - ${NETWORK_NAME}
    depends_on:
      minio:
        condition: service_healthy
      nessie:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
  postgresql_data:
    driver: local

networks:
  shunetwork:
    name: ${NETWORK_NAME}
    driver: bridge
