services:

  # Postgresql Service
  postgresql:
    image: ghcr.io/shugur-network/shudl/postgresql:latest
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    environment:
      - SHUDL_USER=${SHUDL_USER}
      - SHUDL_PASSWORD=${SHUDL_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - PGDATA=/var/lib/postgresql/data/pgdata
      - SHUDL_DB=${SHUDL_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Nessie Service
  nessie:
    image: ghcr.io/shugur-network/shudl/nessie:latest
    container_name: ${COMPOSE_PROJECT_NAME}-nessie
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - NESSIE_VERSION_STORE_TYPE=${NESSIE_VERSION_STORE_TYPE}
      - QUARKUS_DATASOURCE_POSTGRESQL_JDBC_URL=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - QUARKUS_DATASOURCE_POSTGRESQL_USERNAME=${POSTGRES_USER}
      - QUARKUS_DATASOURCE_POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - QUARKUS_HTTP_PORT=${NESSIE_PORT}
      - QUARKUS_HTTP_HOST=${NESSIE_HOST}
    volumes:
      # No persistent volumes
    networks:
      - ${NETWORK_NAME}
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19120/api/v2/config"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

  # Minio Service
  minio:
    image: ghcr.io/shugur-network/shudl/minio:latest
    container_name: ${COMPOSE_PROJECT_NAME}-minio
    environment:
      - MINIO_REGION=${MINIO_REGION}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET_NAME}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=/data
      - MINIO_OPTS=--console-address :9001
    volumes:
      - minio_data:/data
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
  postgresql_data:
    driver: local

networks:
  testnetwork:
    name: ${NETWORK_NAME}
    driver: bridge
