tls_server_config:
  cert_file: /etc/alertmanager/certs/server-cert.pem
  key_file: /etc/alertmanager/certs/server-key.pem
  client_ca_file: /etc/alertmanager/ca/ca-cert.pem
  client_auth_type: RequestClientCert

