# Prometheus Web Configuration (TLS)
# Version: 3.8.0 (verified Nov 28, 2025)
tls_server_config:
  cert_file: /etc/prometheus/certs/server-cert.pem
  key_file: /etc/prometheus/certs/server-key.pem
  client_ca_file: /etc/prometheus/ca/ca-cert.pem
  client_auth_type: RequestClientCert
