apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datalyptica-management

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - pdb.yaml

commonLabels:
  app: alertmanager
  component: monitoring
  managed-by: kustomize
