apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datalyptica-storage

resources:
  - statefulset.yaml
  - service.yaml
  - setup-job.yaml
  - pdb.yaml

commonLabels:
  platform: datalyptica
  tier: storage
  component: minio
