apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jupyterhub
  namespace: datalyptica-management
  labels:
    app: jupyterhub
    layer: analytics
  annotations:
    haproxy.router.openshift.io/timeout: 10m
spec:
  host: jupyter.apps.cluster.local
  to:
    kind: Service
    name: jupyterhub
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
