apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafka-ui
  namespace: datalyptica-management
  labels:
    app: kafka-ui
    layer: management
  annotations:
    haproxy.router.openshift.io/timeout: 5m
spec:
  host: kafka-ui.apps.cluster.local
  to:
    kind: Service
    name: kafka-ui
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
