apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-route.yaml
  - trino-route.yaml
  - minio-route.yaml
  - kafka-ui-route.yaml
  - jupyterhub-route.yaml
  - superset-route.yaml
  - airflow-route.yaml
  - keycloak-route.yaml
  - mlflow-route.yaml
  - prometheus-route.yaml

commonAnnotations:
  description: External routes for Datalyptica services
