apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-console
  namespace: datalyptica-storage
  labels:
    app: minio
    layer: storage
  annotations:
    haproxy.router.openshift.io/timeout: 5m
spec:
  host: minio-console.apps.cluster.local
  to:
    kind: Service
    name: minio-console
    weight: 100
  port:
    targetPort: console
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-api
  namespace: datalyptica-storage
  labels:
    app: minio
    layer: storage
  annotations:
    haproxy.router.openshift.io/timeout: 10m
spec:
  host: minio-api.apps.cluster.local
  to:
    kind: Service
    name: minio
    weight: 100
  port:
    targetPort: api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
