apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: trino
  namespace: datalyptica-data
  labels:
    app: trino
    layer: data
  annotations:
    haproxy.router.openshift.io/timeout: 10m
spec:
  host: trino.apps.cluster.local
  to:
    kind: Service
    name: trino-coordinator
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
