apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datalyptica-control

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  platform: datalyptica
  tier: control
  component: kafka-connect
