apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datalyptica-management

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml

commonLabels:
  app: keycloak
  component: auth
  managed-by: kustomize
