apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-storage-to-control
  namespace: datalyptica-control
  labels:
    layer: security
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    # Allow from storage namespace (PostgreSQL CDC)
    - from:
        - namespaceSelector:
            matchLabels:
              name: datalyptica-storage
      ports:
        - protocol: TCP
          port: 9092 # Kafka
        - protocol: TCP
          port: 8081 # Schema Registry
